### ISSUE TITLE
Assessment Results

### ISSUE THREAD

**Issue by damwhit** [holmesm8/mod_0_skills#1]
@holmesm8 overall, nice work on this. There are a couple of things we'd like for you to update before we consider you `technical ready`:

* [x] Make sure that all of your attributes values are filled in correctly (ie. if it's an integer, we should see an integer as it's value in the example object file)
* [x] Remove the `.` from any method names that includes it. A `.` in programming typically signifies something in computer languages, so be sure to stick to `snake_case` instead.

**Comment by holmesm8** [comment]
Sent a message in slack but I'm going to copy paste it here.

Hey David, I went ahead and updated my files with the changes you listed.
• For the attributes, I went back through to find out what was inconsistent. I think I correctly updated the attributes (so if its a string I referenced a string, etc.). I wasn’t the most confident on booleans so I have it as true and false.
• The methods you mentioned were pretty straight forward, not sure why I had the . in there. I think it was to differentiate my method from the attribute name but I can see how adding that . was a bad idea from your note.

For the classes_2 I ended up pushing two files at once to try it out, but I wasn’t sure if that’s proper or if I should try and keep them separate with different commit names. They were similar changes to both so I kept the commit name the same.

**Comment by damwhit** [comment]
@holmesm8 Really nice job on the updates for the most part. This looks pretty clean. The only issue remaining is that you do not have quotes around your string values. Once that update is made, we'll promote you to `technical ready`. And I think the way you committed is fine!

**Comment by holmesm8** [comment]
@damwhit I've updated both string classes in both the class_1_example_object and class_2_example_object to have the quotes around the string values.
